
import { GeneratedFile, AIModel, Attachment, ChatMessage } from "../types";

const API_BASE = 'http://localhost:3001/api';

export const generateAppCode = async (
  userPrompt: string, 
  model: AIModel, 
  attachments: Attachment[] = [],
  currentFiles: GeneratedFile[] = [],
  history: ChatMessage[] = []
): Promise<GeneratedFile[]> => {
  try {
    const response = await fetch(`${API_BASE}/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt: userPrompt,
        model,
        attachments,
        currentFiles,
        history
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error || 'Generation failed');
    }

    return await response.json();
  } catch (error: any) {
    console.error("API Error:", error);
    throw new Error(error.message || "Failed to connect to OmniGen backend");
  }
};

export const runCodeSimulation = async (files: GeneratedFile[], command: string): Promise<string> => {
  try {
    const response = await fetch(`${API_BASE}/execute`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ files, command })
    });

    if (!response.ok) throw new Error("Execution failed");
    return await response.text();
  } catch (error: any) {
    return `[CONNECTION ERROR]: ${error.message}. Ensure backend is running on port 3001.`;
  }
};

/**
 * Generates initial project scaffolding (package.json, .gitignore)
 * This runs client-side to provide instant feedback before the AI response.
 */
export const setupProject = (projectName: string = 'omnigen-app'): GeneratedFile[] => {
  const files: GeneratedFile[] = [];

  // 1. Package.json
  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: projectName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        "dev": "vite",
        "build": "vite build",
        "lint": "eslint .",
        "preview": "vite preview"
      },
      dependencies: {
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "lucide-react": "^0.344.0",
        "clsx": "^2.1.0",
        "tailwind-merge": "^2.2.1"
      },
      devDependencies: {
        "@vitejs/plugin-react": "^4.2.1",
        "autoprefixer": "^10.4.18",
        "postcss": "^8.4.35",
        "tailwindcss": "^3.4.1",
        "vite": "^5.1.4"
      }
    }, null, 2)
  });

  // 2. .gitignore
  files.push({
    path: '.gitignore',
    content: `node_modules
.DS_Store
dist
dist-ssr
*.local
.env
.vscode/
coverage/
`
  });

  // 3. README.md
  files.push({
    path: 'README.md',
    content: `# ${projectName}

Generated by OmniGen AI.

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Run development server:
   \`\`\`bash
   npm run dev
   \`\`\`
`
  });

  return files;
};
