
import { GeneratedFile, AIModel, Attachment, ChatMessage, GenerationType, Platform, ProgrammingLanguage } from "../types";

const API_BASE = 'http://localhost:3001/api';

export const generateAppCode = async (
  userPrompt: string, 
  model: AIModel, 
  attachments: Attachment[] = [],
  currentFiles: GeneratedFile[] = [],
  history: ChatMessage[] = [],
  platform: Platform = 'web',
  language: ProgrammingLanguage = 'typescript'
): Promise<GeneratedFile[]> => {
  try {
    const response = await fetch(`${API_BASE}/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt: userPrompt,
        model,
        attachments,
        currentFiles,
        history,
        platform,
        language
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error || 'Generation failed');
    }

    return await response.json();
  } catch (error: any) {
    console.error("API Error:", error);
    throw new Error(error.message || "Failed to connect to OmniGen backend");
  }
};

export const runCodeSimulation = async (files: GeneratedFile[], command: string): Promise<string> => {
  try {
    const response = await fetch(`${API_BASE}/execute`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ files, command })
    });

    if (!response.ok) throw new Error("Execution failed");
    return await response.text();
  } catch (error: any) {
    return `[CONNECTION ERROR]: ${error.message}. Ensure backend is running on port 3001.`;
  }
};

export const importGithubRepo = async (repoUrl: string): Promise<GeneratedFile[]> => {
    try {
        const response = await fetch(`${API_BASE}/import/github`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ repoUrl })
        });
        
        if (!response.ok) {
            const err = await response.json();
            throw new Error(err.error || "Failed to import GitHub repository");
        }
        return await response.json();
    } catch (error: any) {
        console.error("GitHub Import Error:", error);
        throw new Error(error.message || "Failed to import GitHub repository");
    }
};

/**
 * Generates initial project scaffolding based on platform and language
 */
export const setupProject = (projectName: string = 'omnigen-app', language: ProgrammingLanguage = 'typescript'): GeneratedFile[] => {
  const files: GeneratedFile[] = [];

  // Basic .gitignore
  files.push({
    path: '.gitignore',
    content: `node_modules\n.DS_Store\ndist\nbuild\n.env\n.vscode/\n__pycache__/\nvenv/\ntarget/`
  });

  // README.md
  files.push({
    path: 'README.md',
    content: `# ${projectName}\n\nGenerated by OmniGen AI.\n\n## Language\n${language}`
  });

  return files;
};
